### PR TITLE
ember-cli pod support

### PR DESCRIPTION
**Pull request by RuslanZavacky**
I've implemented support for --pod syntax. When --pod is provided, fixture will be created in pod path by provided name:

```
$ ember generate fixture example --pod
version: 0.1.5
installing
  create app/pods/example/fixture.js
```

### CODE REVIEW

**Comment by SebastianSzturo** [comment]
Awesome! Thanks for the pull-request

**Comment by RuslanZavacky** [comment]
@lacides @SebastianSzturo guys, can you check it?

**Comment by SebastianSzturo** [comment]
Looks really great. Thank you for your hard work!

**Comment by lacides** [comment]
Hey guys,
Sorry about the delay. I just got back from vacations.
It looks great, I'll take a closer look and merge it later today.
Thanks!

**Comment by lacides** [comment]
Thanks a lot!

**Pull request merged**
